version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: face_app
  app:
    build: ./web
    ports: 
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: run.py
      